### ISSUE TITLE
Error message in the log file

### ISSUE THREAD

**Issue by jsarcone** [dcmeglio/hubitat-bond#7]
I'm getting this error message every so often. Is this an issue 

2020-03-16 08:13:40.749 pm errorgroovy.lang.MissingMethodException: No signature of method: org.apache.http.conn.ConnectTimeoutException.getResponse() is applicable for argument types: () values: []
Possible solutions: getMessage() on line 982 (updateDevices)

Thanks,

Joe

**Comment by apwelsh** [comment]
I just looked at the code and can confirm this is likely a bug.  ConnectTimeoutException does not support getResponse().  I believe the author meant the call to be getMessage() since this is a common method for this scenario.

This is rather benign at this point though. Because your system is not available for the app to talk to.  Likely the IP address may have changed, try making sure your bind has a dhcp reservation on your router. This will ensure the bind never changes IP addresses.

**Comment by jsarcone** [comment]
OK thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bofisher** [comment]
Noticed this as well when I had the device powered down for a few days. A bug, but only an issue if your device changes IP or is offline.

**Comment by dcmeglio** [comment]
I can improve the error logging so it's a bit more useful, but there is nothing I can do if the IP changes. Right now we have a situation where BOND and Hubitat use different technologies. Hubitat uses SSDP as a way to detect IP changes and BOND advertises using mDNS. Hubitat "plans" to add mDNS but there is no timeline. When it is added I'll definitely support it.

**Comment by apwelsh** [comment]
To be clear @dcmeglio , What I am referring to is

```
checkHttpResponse("getState",` e.getResponse())
```

the java Exception class, which is what the code catches, does not have a getResponse() method.  I believe what you want is e.getMessage() and to create another parser that beautifies the Java Throwable's message to a log message.  100% every as depicted above will throw an exception, since no throwable offers getResponse() as a method.

Personally, I would just change it to
```
log.error "getState: Unexpected HTTP failure: ${e.getMessage()}"
```

**Comment by dcmeglio** [comment]
@apwelsh thanks for the clarification. Yup, I added a nicer catch for the Connection Timeout. That being said, hopefully one day I can prevent the root cause using mDNS.

**Comment by jsarcone** [comment]
No. I still get the error even though I have a static IP.
